### ISSUE TITLE
icons

### ISSUE THREAD

**Issue by ncmprhnsbl** [labwc/labwc-menu-generator#24]
i notice that labwc-menu-generator includes icons in it's output (since i've taken to using it with openbox).   
is this an intentional inclusion? because i see that menu icons is currently out of scope for labwc, so whether they're present in the output is irrelevant there.
i suppose where i'm going with this, is to request(or suggest) an option to exclude icons (or include).

**Comment by johanmalm** [comment]
Thanks for writing.

We include the icon name because we parse the desktop file anyway, so it's got virtually no overhead. I use those icon names in another personal project, so find it handy to have them.

IIRC openbox actually needs the full path (e.g. `/usr/share/icons/Papirus/whatever/foo.png`). We currently don't support finding icons against theme and size, but it would be quite straight forward to add.
Would probably just bundle `https://gitlab.freedesktop.org/vyivel/libsfdo` with it.
Is that what you're looking for?

**Comment by ncmprhnsbl** [comment]
> IIRC openbox actually needs the full path   

yes, this is correct and the only reason i was seeing any icons in openbox was because of the rare cases of *.desktops including the full path.
>Is that what you're looking for?   

not me, my preference is no icons :)
up to you of course, but i wouldn't bother unless you intend to enable icons in labwc's menu (and in that case that it be optional).

my first workaround for this was to pipe the output through sed: `sed '/icon=".\+"/ s///g'` (pretty silly)
then, after looking at the source, i saw that it's a simple matter to remove the icon parts.
i made a fork with a 'no-icon' branch for anybody who's interested : now deleted

**Comment by johanmalm** [comment]
Fixed by #25

**Comment by ncmprhnsbl** [comment]
nice :) thanks 
deleted my now redundant fork.
